# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.move import Move  # noqa: F401,E501
from swagger_server import util


class OpeningVariant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, moves: List[Move]=None):  # noqa: E501
        """OpeningVariant - a model defined in Swagger

        :param name: The name of this OpeningVariant.  # noqa: E501
        :type name: str
        :param moves: The moves of this OpeningVariant.  # noqa: E501
        :type moves: List[Move]
        """
        self.swagger_types = {
            'name': str,
            'moves': List[Move]
        }

        self.attribute_map = {
            'name': 'name',
            'moves': 'moves'
        }

        self._name = name
        self._moves = moves

    @classmethod
    def from_dict(cls, dikt) -> 'OpeningVariant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpeningVariant of this OpeningVariant.  # noqa: E501
        :rtype: OpeningVariant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this OpeningVariant.

        The human friendly name for the variant  # noqa: E501

        :return: The name of this OpeningVariant.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OpeningVariant.

        The human friendly name for the variant  # noqa: E501

        :param name: The name of this OpeningVariant.
        :type name: str
        """

        self._name = name

    @property
    def moves(self) -> List[Move]:
        """Gets the moves of this OpeningVariant.

        The moves that identify this variant  # noqa: E501

        :return: The moves of this OpeningVariant.
        :rtype: List[Move]
        """
        return self._moves

    @moves.setter
    def moves(self, moves: List[Move]):
        """Sets the moves of this OpeningVariant.

        The moves that identify this variant  # noqa: E501

        :param moves: The moves of this OpeningVariant.
        :type moves: List[Move]
        """

        self._moves = moves
