"""init

Revision ID: 45085c71ff0f
Revises: 
Create Date: 2019-02-26 01:22:53.352643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45085c71ff0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('opening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eco', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.String(length=128), nullable=False),
    sa.Column('turn', sa.Boolean(), nullable=False),
    sa.Column('white_can_castle_queenside', sa.Boolean(), nullable=False),
    sa.Column('white_can_castle_kingside', sa.Boolean(), nullable=False),
    sa.Column('black_can_castle_queenside', sa.Boolean(), nullable=False),
    sa.Column('black_can_castle_kingside', sa.Boolean(), nullable=False),
    sa.Column('en_passant_square', sa.Integer(), nullable=True),
    sa.Column('halfmove_clock', sa.Integer(), nullable=False),
    sa.Column('fullmove_number', sa.Integer(), nullable=False),
    sa.Column('is_checkmate', sa.Boolean(), nullable=False),
    sa.Column('is_stalemate', sa.Boolean(), nullable=False),
    sa.Column('is_check', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pieces', 'turn', 'white_can_castle_queenside', 'white_can_castle_kingside', 'black_can_castle_queenside', 'black_can_castle_kingside', 'en_passant_square', 'halfmove_clock', 'fullmove_number')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_pos_id', sa.Integer(), nullable=False),
    sa.Column('end_pos_id', sa.Integer(), nullable=False),
    sa.Column('src', sa.Integer(), nullable=False),
    sa.Column('dst', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_pos_id'], ['position.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_pos_id'], ['position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_pos_id', 'end_pos_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('game_move',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'move_id')
    )
    op.create_table('opening_move',
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opening_id'], ['opening.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opening_id', 'move_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_move')
    op.drop_table('game_move')
    op.drop_table('user_role')
    op.drop_table('move')
    op.drop_table('game_header')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('position')
    op.drop_table('opening')
    op.drop_table('game')
    # ### end Alembic commands ###
