"""playlists

Revision ID: b907c83dabf0
Revises: 9e652480efe2
Create Date: 2019-03-03 21:11:22.223593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b907c83dabf0'
down_revision = '9e652480efe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_playlist_game',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['game_playlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'game_id')
    )
    op.create_table('opening_playlist_opening',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opening_id'], ['opening.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['opening_playlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'opening_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_playlist_opening')
    op.drop_table('game_playlist_game')
    op.drop_table('opening_playlist')
    op.drop_table('game_playlist')
    # ### end Alembic commands ###
